export enum UserError {
  NOT_FOUND = 'USER_ERROR.NOT_FOUND',
  EMAIL_EMPTY = 'USER_ERROR.BAD_REQUEST.EMAIL_EMPTY',
  EMAIL_INVALID = 'USER_ERROR.BAD_REQUEST.EMAIL_INVALID',
  EMAIL_ALREADY_EXISTS = 'USER_ERROR.CONFLICT.EMAIL_ALREADY_EXISTS',
  ROLE_EMPTY = 'USER_ERROR.BAD_REQUEST.ROLE_EMPTY',
  ROLE_INVALID = 'USER_ERROR.BAD_REQUEST.ROLE_INVALID',
  PASSWORD_EMPTY = 'USER_ERROR.BAD_REQUEST.PASSWORD_EMPTY',
  PASSWORD_TOO_SHORT = 'USER_ERROR.BAD_REQUEST.PASSWORD_TOO_SHORT',
}
